config/routes.rb
Rails.application.routes.draw do
  resources :boeufs
  get "apropos" , to: "boeufs#apropos"
  get "index" , to: "boeufs#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "boeufs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boeuf.rb
class Boeuf < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boeufs_controller.rb
class BoeufsController < ApplicationController
  before_action :set_boeuf, only: %i[ show edit update destroy ]

  # GET /boeufs or /boeufs.json
  def index
    @boeufs = Boeuf.all
  end

  # GET /boeufs/1 or /boeufs/1.json
  def show
  end

  # GET /boeufs/new
  def new
    @boeuf = Boeuf.new
  end

  # GET /boeufs/1/edit
  def edit
  end

  # POST /boeufs or /boeufs.json
  def create
    @boeuf = Boeuf.new(boeuf_params)

    respond_to do |format|
      if @boeuf.save
        format.html { redirect_to boeuf_url(@boeuf), notice: "Boeuf was successfully created." }
        format.json { render :show, status: :created, location: @boeuf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @boeuf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boeufs/1 or /boeufs/1.json
  def update
    respond_to do |format|
      if @boeuf.update(boeuf_params)
        format.html { redirect_to boeuf_url(@boeuf), notice: "Boeuf was successfully updated." }
        format.json { render :show, status: :ok, location: @boeuf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @boeuf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boeufs/1 or /boeufs/1.json
  def destroy
    @boeuf.destroy!

    respond_to do |format|
      format.html { redirect_to boeufs_url, notice: "Boeuf was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boeuf
      @boeuf = Boeuf.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def boeuf_params
      params.require(:boeuf).permit(:image, :duration, :difficult, :kcal, :name, :description, :carbohydrates, :proteins, :lipids, :ingredient, :quantity, :ingredient2, :quantity2, :ingredient3, :quantity3, :ingredient4, :quantity4, :ingredient5, :quantity5, :ingredient6, :quantity6, :ingredient7, :quantity7, :ingredient8, :quantity8, :ingredient9, :quantity9, :step_description, :step2, :step3, :step4, :step5, :step6, :step7, :step8, :step9 )
    end
end

app/controllers/concerns/apropos_controller.rb
class AproposController < ApplicationController
  def apropos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boeufs_helper.rb
module BoeufsHelper
end

app/views/boeufs/_boeuf.html.erb
<div class="container card" id="<%= dom_id boeuf %>" >


  <img class="img_boeuf" src="<%= boeuf.image %>" alt="">
  <!-- Première partie de la carte recette avec le temps, la difficulté et le nombre de Kcal-->
  <div class="container intro">
    <div class="icone">
      <img src="https://cdn-icons-png.flaticon.com/512/27/27133.png" alt="icone timer">
      <h5>
        <strong><%= boeuf.duration %>min</strong>
      </h5>
      <p>
        Durée
      </p>
    </div>
    <div class="icone">
      <img src="https://cdn-icons-png.flaticon.com/512/65/65061.png" alt="icone timer">
      <div class="indic">
        <h5>
          <strong><%= boeuf.difficult %></strong>
        </h5>
        <p>
          Difficulté
        </p>
      </div>
    </div>
    <div class="icone">
      <img src="https://static.thenounproject.com/png/1166850-200.png" alt="icone timer">
      <h5>
        <strong><%= boeuf.kcal %></strong>
      </h5>
      <p>
        Kcal
      </p>
    </div>
  </div>

  <h2 class="container">
    <strong><%= boeuf.name %></strong>
  </h2>

  <p class="container">
    <%= boeuf.description %>
  </p>
  <!--Partie valeur nutritionnelles de la recette-->
  <div class="container nutrition_value">
    <h3>Informations nutritionnelles</h3>
    <div class="nutrition">
      <p>
        <strong>Glucides:</strong>
      </p>
      <p>
        <%= boeuf.carbohydrates %>g
      </p>
    </div>
    <div class="nutrition"> 
      <p>
        <strong>Protéines:</strong>
      </p>
      <p>
        <%= boeuf.proteins %>g
      </p>
    </div>
    <div class="nutrition">
      <p>
        <strong>Lipides:</strong>
      </p>
      <p>
        <%= boeuf.lipids %>g
      </p>
    </div>
  </div>

  <!-- Partie ingrédient-->
  <% if boeuf.ingredient.present? %>
  <div class="container">
    <div class="ingredients">
      <p>
        <strong><%= boeuf.ingredient %></strong>
      </p>

      <p>
        <%= boeuf.quantity %>
      </p>
    </div>
    <% end %>

    <% if boeuf.ingredient2.present? %>
    <div class="ingredients">
      <p>
        <strong><%= boeuf.ingredient2 %></strong>
      </p>

      <p>
        <%= boeuf.quantity2 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.ingredient3.present? %>
    <div class="ingredients">
      <p>
        <strong><%= boeuf.ingredient3 %></strong>
      </p>

      <p>
        <%= boeuf.quantity3 %>
      </p>
    </div>
    <% end%>

    <% if boeuf.ingredient4.present? %>
      <div class="ingredients">
        <p>
          <strong><%= boeuf.ingredient4 %></strong>
        </p>

        <p>
          <%= boeuf.quantity4 %>
        </p>
      </div>
    <% end%>

    <% if boeuf.ingredient5.present? %>
      <div class="ingredients">
        <p>
          <strong><%= boeuf.ingredient5 %></strong>
        </p>

        <p>
          <%= boeuf.quantity5 %>
        </p>
      </div>
    <% end%>

    <% if boeuf.ingredient6.present? %>
      <div class="ingredients">
        <p>
          <strong><%= boeuf.ingredient6 %></strong>
        </p>

        <p>
          <%= boeuf.quantity6 %>
        </p>
      </div>
    <% end %>

    <% if boeuf.ingredient7.present? %>
    <div class="ingredients">
      <p>
        <strong><%= boeuf.ingredient7 %></strong>
      </p>

      <p>
        <%= boeuf.quantity7 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.ingredient8.present? %>
    <div class="ingredients">
      <p>
        <strong><%= boeuf.ingredient8 %></strong>
      </p>

      <p>
        <%= boeuf.quantity8 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.ingredient9.present? %>
    <div class="ingredients">
      <p>
        <strong><%= boeuf.ingredient9 %></strong>
      </p>

      <p>
        <%= boeuf.quantity9 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.step_description.present? %>
    <div class="steps">
      <h5><strong>Etape </strong><h5>
      <p>
        <%= boeuf.step_description %>
      </p>
    </div>
    <% end %>

    <% if boeuf.step2.present? %>
    <div class="steps">
      <p>
        <%= boeuf.step2 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.step3.present? %>
    <div class="steps">
      <p>
        <%= boeuf.step3 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.step4.present? %>
    <div class="steps">
      <p>
        <%= boeuf.step4 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.step5.present? %>
    <div class="steps">
      <p>
        <%= boeuf.step5 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.step6.present? %>
    <div class="steps">
      <p>
        <%= boeuf.step6 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.step7.present? %>
    <div class="steps">
      <p>
        <%= boeuf.step7 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.step8.present? %>
    <div class="steps">
      <p>
        <%= boeuf.step8 %>
      </p>
    </div>
    <% end %>

    <% if boeuf.step9.present? %>
    <div class="steps">
      <p>
        <%= boeuf.step9 %>
      </p>
    </div>
    <% end %>
  </div>

</div>

app/views/boeufs/_form.html.erb
<%= form_with(model: boeuf) do |form| %>
  <% if boeuf.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(boeuf.errors.count, "error") %> prohibited this boeuf from being saved:</h2>

      <ul>
        <% boeuf.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_area :image %>
  </div>

  <div>
    <%= form.label :durée, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :difficulté, style: "display: block" %>
    <%= form.text_field :difficult %>
  </div>

  <div>
    <%= form.label :kcal, style: "display: block" %>
    <%= form.number_field :kcal %>
  </div>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :glucides, style: "display: block" %>
    <%= form.text_field :carbohydrates %>
  </div>

  <div>
    <%= form.label :protéines, style: "display: block" %>
    <%= form.text_field :proteins %>
  </div>

  <div>
    <%= form.label :lipides, style: "display: block" %>
    <%= form.text_field :lipids %>
  </div>

  <div>
    <%= form.label :ingrédient1, style: "display: block" %>
    <%= form.text_field :ingredient %>
  </div>

  <div>
    <%= form.label :quantité1, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.label :ingrédient2, style: "display: block" %>
    <%= form.text_field :ingredient2 %>
  </div>

  <div>
    <%= form.label :quantité2, style: "display: block" %>
    <%= form.text_field :quantity2 %>
  </div>

  <div>
    <%= form.label :ingrédient3, style: "display: block" %>
    <%= form.text_field :ingredient3 %>
  </div>

  <div>
    <%= form.label :quantité3, style: "display: block" %>
    <%= form.text_field :quantity3 %>
  </div>

  <div>
    <%= form.label :ingrédient4, style: "display: block" %>
    <%= form.text_field :ingredient4 %>
  </div>

  <div>
    <%= form.label :quantité4, style: "display: block" %>
    <%= form.text_field :quantity4 %>
  </div>

  <div>
    <%= form.label :ingrédient5, style: "display: block" %>
    <%= form.text_field :ingredient5 %>
  </div>

  <div>
    <%= form.label :quantité5, style: "display: block" %>
    <%= form.text_field :quantity5 %>
  </div>

  <div>
    <%= form.label :ingrédient6, style: "display: block" %>
    <%= form.text_field :ingredient6 %>
  </div>

  <div>
    <%= form.label :quantité6, style: "display: block" %>
    <%= form.text_field :quantity6 %>
  </div>

  <div>
    <%= form.label :ingrédient7, style: "display: block" %>
    <%= form.text_field :ingredient7 %>
  </div>

  <div>
    <%= form.label :quantité7, style: "display: block" %>
    <%= form.text_field :quantity7 %>
  </div>

  <div>
    <%= form.label :ingrédient8, style: "display: block" %>
    <%= form.text_field :ingredient8 %>
  </div>

  <div>
    <%= form.label :quantité8, style: "display: block" %>
    <%= form.text_field :quantity8 %>
  </div>

  <div>
    <%= form.label :ingrédient9, style: "display: block" %>
    <%= form.text_field :ingredient9 %>
  </div>

  <div>
    <%= form.label :quantité9, style: "display: block" %>
    <%= form.text_field :quantity9 %>
  </div>

  <div>
    <%= form.label :etape1, style: "display: block" %>
    <%= form.text_area :step_description %>
  </div>

  <div>
    <%= form.label :etape2, style: "display: block" %>
    <%= form.text_area :step2 %>
  </div>

  <div>
    <%= form.label :etape3, style: "display: block" %>
    <%= form.text_area :step3 %>
  </div>

  <div>
    <%= form.label :etape4, style: "display: block" %>
    <%= form.text_area :step4 %>
  </div>

  <div>
    <%= form.label :etape5, style: "display: block" %>
    <%= form.text_area :step5 %>
  </div>

  <div>
    <%= form.label :etape6, style: "display: block" %>
    <%= form.text_area :step6 %>
  </div>

  <div>
    <%= form.label :etape7, style: "display: block" %>
    <%= form.text_area :step7 %>
  </div>

  <div>
    <%= form.label :etape8, style: "display: block" %>
    <%= form.text_area :step8 %>
  </div>

  <div>
    <%= form.label :etape9, style: "display: block" %>
    <%= form.text_area :step9 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
    
</div>
<div id="items">
</div>

app/views/boeufs/apropos.html.erb
<title>A Propos</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<link rel="stylesheet" href="../../assets/stylesheets/apropos.scss">
<link rel="stylesheet" href="../../assets/stylesheets/application.scss">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <div class="container box_propos" >
            <img src="https://media.licdn.com/dms/image/D4E35AQFrCm1UK1hqhA/profile-framedphoto-shrink_400_400/0/1698617462562?e=1711281600&v=beta&t=VCuNLb52DE2UZ9_b3rKV8uGLJcWWWwCraTjJS-pZFuQ" alt="image Antoine CORBERAND">
        <div class="para_apropos">
            <h2>
                développeur front junior
            </h2>
            <p>
                Je m’appelle Antoine, étant passionné par le monde du web et dû 
                design. J’ai donc décidé de poursuivre mes études et mon parcours
                professionnel dans ce domaine, actuellement en 1re année de 
                BUT MMI.(Métier du Multimédia et de l’Internet)J’aimerai 
                me diriger vers le métier d’intégrateur web ou développeur 
                Front-End.
            </p>
            <div class="link">
                <a href="https://www.linkedin.com/in/antoine-corberand-49898b294/">
                    <img src="https://cdn-icons-png.flaticon.com/512/61/61109.png" alt="icone linkedin">
                </a>
                <a href="https://antoine-corberand.netlify.app">
                    <img src="https://antoine-corberand.netlify.app/img/ordinateur.svg" alt="icone portfolio">
                </a>
            </div>
        </div>
    </div>

    <div class="container box_propos">
        <div class="img_apropos">
            <img src="https://media.licdn.com/dms/image/D4E03AQE4GKbzHCEtvg/profile-displayphoto-shrink_400_400/0/1696495012598?e=1716422400&v=beta&t=aUPOBwjFTqElAemA8zGvIeJQoFtttCy5Ro4Rs4MdXFE" alt="image Antoine COURCAUD">
        </div>
        <div class="para_apropos">
            <h2>
                développeur de visibilité sur les réseaux sociaux
            </h2>
            <p>
                Passionné par le numérique, je suis actuellement en BUT 
                MMI à l’université Bordeaux Montaigne.<br>
                J’ai choisi de suivre cette formation pour 
                gagner en compétences et acquérir de bonnes bases 
                dans les domaines de la création, du développement 
                et de l’analyse de données.<br>Durant cette première année, 
                j’ai participé à de nombreux projets comme l’analyse du compte 
                Instagram d’une chef cuisinière, la refonte d’un site 
                web ou encore la réalisation d’un motion design, 
                tous consultables sur mon Portfolio. <br>Parallèlement 
                à mes études, je développe des comptes Instagram que 
                j’anime et qui me permettent de mettre en place les 
                compétences que j’ai acquises grâce à ma formation. <br>
                À partir de ma deuxième année, 
                je souhaiterais appliquer ces compétences 
                dans le cadre d’une alternance en entreprise qui me permettra 
                de me spécialiser dans le marketing digital. <br>Je suis 
                notamment intéressé par l’optimisation du SEO, la création 
                et l’animation de contenus sur les réseaux sociaux et 
                l’analyse des données web pour optimiser les performances 
                de stratégies marketing. Je suis persuadé que ce sera une 
                opportunité enrichissante.<br>
                Dynamisme et autonomie sont des atouts qui me caractérisent. 
                Je suis également très organisé et efficace dans tout ce que 
                j’entreprends. <br>
                N'hésitez pas à me contacter si vous avez une offre 
                d'alternance à me proposer.
            </p>
            <a href="https://www.linkedin.com/in/antoine-courcaud/">
                <img src="https://cdn-icons-png.flaticon.com/512/61/61109.png" alt="icone linkedin">
            </a>
        </div>
    </div>

    <%= yield %>

</body>


</html>

app/views/boeufs/edit.html.erb
<link rel="stylesheet" href="../../stylesheets/application.scss">

<h1 class="h1_edit">Editer</h1>

<div class="d-grid gap-2 col-6 mx-auto">
<%= render "form", boeuf: @boeuf %>
</div>
<br>

<div>
  <%= link_to "Show this boeuf", @boeuf %> |
  <%= link_to "Retour", boeufs_path %>
</div>

app/views/boeufs/index.html.erb
<!-- Header -->
<link rel="stylesheet" href="../../stylesheets/application.scss">

  <div class="img_header">
    <div class="container text_header">
      <h1>
        <strong>LIBEREZ VOTRE POTENTIEL</strong>
      </h1>
      <p>
        Explorez un monde de saveurs tout en atteignant vos objectifs grâce à des recettes adaptées
      </p>
    </div>
    <img src="https://antoine.courcaud.fr/header.png" alt="image header">
  </div>

  <div>
    <p class="text-recette">
      Choisis ta recette
    </p>
    <p class="descriptif-top">
      Avec notre collection de recettes variées, nous avons de quoi satisfaire tous vos objectifs.
    <p>

  </div>

<p style="color: green"><%= notice %></p>

<div id="boeufs">
  <div class="box_food row">
  <div class="col-md-6">
  <% @boeufs.each do |boeuf| %>
    <%= render boeuf %>
    <div class="container new-container">
      <a>
        <button class="button_show">
          <strong><%= link_to "Voir la recette", boeuf %></strong>
        </button>
      </a>
    </div>
  </div>
  <div class="col-md-6">
  <% end %>
  </div>
</div>
    <div class="container new-container2">
      <a>
      <button class="button_new">
      <strong><%= link_to "Nouvelle recette", new_boeuf_path %></strong>
      </button>
    
    </div>

app/views/boeufs/new.html.erb
<h1 class="h1_edit">New boeuf</h1>

<div class="d-grid gap-2 col-6 mx-auto">
<%= render "form", boeuf: @boeuf %>
</div>

<br>

<div>
  <%= link_to "Retour", boeufs_path %>
</div>

app/views/boeufs/show.html.erb
<link rel="stylesheet" href="../../stylesheets/application.scss">

<p style="color: green"><%= notice %></p>

<%= render @boeuf %>

<div class="container button_edit">
  <div>
    <a>
      <button class="button_new">
        <strong><%= link_to "Modifier la recette", edit_boeuf_path(@boeuf) %></strong>
      </button>
    </a>
  </div>
  <div class="">
    <a>
      <button class="button_show">
        <strong><%= link_to "Retour", boeufs_path %></strong>
      </button>
    </a>
  </div>
  <a class="button_destroy">
  <%= button_to "Supprimer", @boeuf, method: :delete %>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kcaldata</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <div class="container-flouid">
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container menu">
          <a class="navbar-brand" href="/">
            <%= image_tag("Group.svg") %>
            <p class="title-logo"> Kcal
                Data
            </p>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav text-center me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="<%=index_path %>">Accueil</a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
               <a class="nav-link" href="<%=apropos_path %>"> A propos
                </a>
              </li>
            </ul>
            <a class="abonnement" href="mailto:antoine.courcaud@gmail.com">
            <button class="contact">Nous contacter</button>
            </a>

        </div>
      </div>
    </nav>
  </div>
</header>





    <%= yield %>


<footer id="footer">
  <div class="logo_footers">
    <%= image_tag("Group.svg") %>
    <p class="text-logo">
      <strong>Kcal Data<strong>
    </p>
  </div>
  <p>
    <ul class="links">
      <li><a href="apropos.html">A propos</a></li>
      <li><a href="application.html">Accueil</a></li>
    </ul>
  </p>
    <div class="social-icons">
      <%= image_tag("tiktok.svg") %>
      <%= image_tag("facebook.svg") %>
      <%= image_tag("instagram.svg") %>
      <%= image_tag("youtube.svg") %>
    </div>
    <p class="copy_footer">
      © 2024 Kcal Data.
    </p>
</footer>

</body>
</html>